# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

CERRA :
  type : anemoi
  anemoi_config:
    dataset: 'cerra-rr-an-oper-se-al-ec-mars-5p5km-1985-2023-3h-v2'
    trim_edge: 100 #755161 for 100, 470k points left for 200
  stream_id : 1
  #filenames : ['cerra-rr-an-oper-se-al-ec-mars-5p5km-1985-2023-3h-v2.zarr']
  source : [ 'skt', 'sp', '10si', '10wdir', '2r', '2t', 'msl', 'r_100', 'r_1000', 'r_150', 'r_200', 'r_250', 'r_300', 'r_400', 'r_50', 'r_500', 'r_600', 'r_700', 'r_850', 'r_925', 't_100', 't_1000', 't_150', 't_200', 't_250', 't_300', 't_400', 't_50', 't_500', 't_600', 't_700', 't_850', 't_925', 'u_100', 'u_1000', 'u_150', 'u_200', 'u_250', 'u_300', 'u_400', 'u_50', 'u_500', 'u_600', 'u_700', 'u_850', 'u_925', 'v_100', 'v_1000', 'v_150', 'v_200', 'v_250', 'v_300', 'v_400', 'v_50', 'v_500', 'v_600', 'v_700', 'v_850', 'v_925', 'z_100', 'z_1000', 'z_150', 'z_200', 'z_250', 'z_300', 'z_400', 'z_50', 'z_500', 'z_600', 'z_700', 'z_850', 'z_925']
  target : [ 'skt', 'sp', '10si', '10wdir', '2r', '2t', 'msl', 'r_100', 'r_1000', 'r_150', 'r_200', 'r_250', 'r_300', 'r_400', 'r_50', 'r_500', 'r_600', 'r_700', 'r_850', 'r_925', 't_100', 't_1000', 't_150', 't_200', 't_250', 't_300', 't_400', 't_50', 't_500', 't_600', 't_700', 't_850', 't_925', 'u_100', 'u_1000', 'u_150', 'u_200', 'u_250', 'u_300', 'u_400', 'u_50', 'u_500', 'u_600', 'u_700', 'u_850', 'u_925', 'v_100', 'v_1000', 'v_150', 'v_200', 'v_250', 'v_300', 'v_400', 'v_50', 'v_500', 'v_600', 'v_700', 'v_850', 'v_925', 'z_100', 'z_1000', 'z_150', 'z_200', 'z_250', 'z_300', 'z_400', 'z_50', 'z_500', 'z_600', 'z_700', 'z_850', 'z_925']
  geoinfo_channels : [ 'insolation', 'cos_local_time', 'sin_local_time', 'cos_julian_day', 'sin_julian_day']
  loss_weight : 1.
  token_size : 16
  max_num_targets: 375000 #131072 #131072 # 262144   #131072 # 65536 #32768 #8192
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  # pred_spatial_shared: ERA5
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1
