evaluation:
  metrics  : 
  - rmse
  # metrics  : ["rmse", "mae"]
  # regions: ["global", "nhem"] # Have regions here, if you want for them to apply to all streams (scores calculation)
  summary_plots : true
  ratio_plots : false
  heat_maps : false
  summary_dir: "./plots/std_debug"
  plot_ensemble: "members" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation
  plot_score_animations: false #plot animations of score maps across forecast steps. it slows down score computation
  plot_score_timeseries: false #plot timeseries of scores across forecast steps. 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: false
  # baseline: "ar40mckx"


default_streams:
  ERA5ml:
    #offset: "1h" #optional: specify a timedelta offset to infer init_time when source_interval is missing. Format examples: "1h", "30m", "2h30m".
    regions: ["global"]
    channels: ["2t", "10u", "10v", "z_500", "t_850", "u_850", "v_850", "q_850", ]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all" #supported: "all", "mean", [0,1,2]
    plotting:
      sample: [0]
      forecast_step: "all" #supported: "all", [1,2,3,...], "1-50" (equivalent of [1,2,3,...50])
      ensemble: "std" #supported: "all", "mean", [0,1,2]
      plot_maps: true
      plot_bias: false
      plot_target: false
      plot_histograms: false
      plot_animations: false
 
      
run_ids :
  bgra397w:
    label: "ensemble_eval"
    #results_base_dir : "./results/"
    #NEW: if "streams" is not specified, the default streams are used
    
      
 