
global_plotting_options:
 regions: ["cerra"]
 image_format : "png" 
 dpi_val : 500
 fps: 2

evaluation:
  metrics  :
    - psd:
        psd_method: "fft"    
  regions: ["cerra"]
  summary_plots : true
  ratio_plots : true
  heat_maps : false
  summary_dir: "./plots/KNMI/eval_plots/psd_cerra_6"
  plot_ensemble: false #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: true
  num_processes: "auto"  #options: int, "auto", 0 means no parallelism (default)
  
default_streams:
  CERRA_OUT_1:
    channels: ['r_700','r_850','r_925']
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all"
  CERRA_OUT_2:
    channels: ['r_850']
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all"
  CERRA_OUT_3:
    channels: ['r_925']
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all"

      
run_ids :
      qs5lo1ud:
          label: "5: input: 72 vars, 1 decoder for r_850"
          color: "#0072B2"
          rank: "all"
      nobjggqt:
          label: "6_1: input: 72 vars, 1 decoder for r_700, r_850, r_925"
          color: "#E69F00"
          rank: "all"
      lzeitk6a:
          label: "6_2: input: 72 vars, 3 decoders for r_700, r_850, r_925"
          color: "#009E73"
          rank: "all"
      