
global_plotting_options:
 regions: ["cerra"]
 image_format : "png" 
 dpi_val : 500
 fps: 2

evaluation:
  #metrics  : ["rmse"]
  metrics  :
    - psd:
        psd_method: "fft"   
  regions: ["cerra"]
  summary_plots : true
  ratio_plots : true
  heat_maps : false
  summary_dir: "./plots/KNMI/eval_plots/cerra_7vars_psd_10_9"
  plot_ensemble: false #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: true
  num_processes: "auto"  #options: int, "auto", 0 means no parallelism (default)
  
default_streams:
  CERRA:
    channels: ["2t", "msl", "r_850", "t_850", "u_850", "v_850", "z_850"] #, "blah"]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all"
    # plotting:
    #   sample: [1,2,3]
    #   forecast_step: "all"
    #   ensemble: "mean"
    #   plot_maps: true
    #   plot_bias: true
    #   plot_target: true
    #   plot_histograms: true
    #   plot_animations: true
      
run_ids :


      # clhc6j4r:
      #   label: "CERRA - 3h - abscoords -  72 vars source, 7 vars target - epoch 128"
      #   color: "tab:red"
      #   rank: "all"

      # mwh3hffs:
      #     label: "CERRA - 3h - abscoords -  72 vars source, 7 vars target - epoch 176"
      #     color: "tab:blue"
      #     rank: "all"
      
      # rhqaa4b4:
      #     label: "CERRA - 3h - abscoords -  72 vars source, 72 vars target - epoch 128"
      #     color: "tab:orange"
      #     rank: "all"

      # bmd5xg2e:
      #     label: "CERRA - 3h - abscoords -  72 vars source, 72 vars target - epoch 176"
      #     color: "tab:green"
      #     rank: "all"

      ymsz4voj:
          label: "CERRA - 3h - abscoords -  7 vars source, 7 vars target - epoch 128"
          color: "tab:purple"
          rank: "all"

      # amru9kuw:
      #     label: "CERRA - 3h - abscoords -  7 vars source, 7 vars target - epoch 176"
      #     color: "tab:pink"
      #     rank: "all"

      # cw89g975:
      #     label: "CERRA - 3h - abscoords -  7 vars source, 7 vars target - epoch 256"
      #     color: "tab:brown"
      #     rank: "all"


      



