# "_" means new stage of Curriculum Learning
# "+" means streams are used jointly
# (start_year-num_epochs)
train:
  plot:
      fgorjblh:
          slurm_id: 0
          description: "ERA5-O96+CERRA(1985-64)"
      fbclk6da:
          slurm_id : 0
          description : "ERA5-O96(1985-64)_ERA5-O96+CERRA(2014-16)"
      bawkrdsg:
          slurm_id : 0
          description : "ERA5-O96(1985-32)_ERA5-O96+CERRA(2014-32)"
      a2ljwguv:
          slurm_id : 0
          description : "ERA5-O96(1985-32)_ERA5-O96+CERRA(1985-32)"
      
      
      