global_plotting_options:
  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
  regions: ["global"]
  dpi_val : 300
  ERA5:
    marker_size: 4

evaluation:
  metrics  : ["froct", "rmse"]
  regions: ["global"]
  summary_plots : true
  summary_dir: "./plots/"
  print_summary: false #print out score values on screen. it can be verbose
  plot_score_maps: false
  log_scale: false
  add_grid: true

run_ids :
  bcf5s0uy:
    label: "My model"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: [0]
          forecast_step: 1-39
          plot_maps: true
          plot_animations: true
          plot_histograms: false
