# "_" means new stage of Curriculum Learning
# "+" means streams are used jointly
# (start_year-num_epochs)
train:
  plot:
      anxd2cq5:
          slurm_id: 0
          description: "ERA5-O96(1985-64)_ERA5-N320(2014-16)_ERA5-N320+CERRA(2014-16)"
      ghpe27y4:
          slurm_id: 0
          description: "ERA5-O96(1985-64)_ERA5-N320(2014-16)_ERA5-N320+CERRA(2014-16)+LW2"
      bj7kdv4m:
          slurm_id: 0
          description: "ERA5-O96(1985-64)_ERA5-N320(2014-16)_ERA5-N320+CERRA(2014-16)+LW5"
      