data_loading:
  num_workers: 2
test_config:
  start_date: 2023-10-01T00:00
  end_date: 2023-12-31T23:59
  output:
    num_samples: 120
  samples_per_mini_epoch: 120
  forecast:
    num_steps: 9
streams_directory: ./config/inference/streams/era5_o96_IO_cerra_IO/